import type { NodeTemplate } from './types';

export const NODE_TEMPLATES: NodeTemplate[] = [
  {
    type: 'start_python',
    label: 'Start (Python)',
    category: 'Lifecycle',
    defaultConfig: {
      functionName: 'setup_context',
      code: 'def setup_context(context):\n    return context\n',
    },
  },
  {
    type: 'start_request',
    label: 'Start (Request)',
    category: 'Lifecycle',
    defaultConfig: {
      method: 'GET',
      url: 'https://api.example.com/bootstrap',
      authRef: '',
      timeoutMs: 10000,
      retryAttempts: 3,
      backoff: 'exponential',
    },
  },
  { type: 'end', label: 'End', category: 'Lifecycle', defaultConfig: {} },
  { type: 'if', label: 'If', category: 'Control', defaultConfig: { expression: 'vars.status == "ok"' } },
  {
    type: 'define_variable',
    label: 'Define Variable',
    category: 'Control',
    defaultConfig: { name: 'new_var', selector: 'body.data.id', source: 'last_response', defaultValue: '' },
  },
  {
    type: 'for_each_parallel',
    label: 'For Each (Parallel)',
    category: 'Control',
    defaultConfig: { listExpr: 'vars.items', itemName: 'item', maxConcurrency: 5 },
  },
  { type: 'join', label: 'Join', category: 'Control', defaultConfig: { mergeStrategy: 'collect_list' } },
  {
    type: 'form_request',
    label: 'Form Request',
    category: 'Requests',
    defaultConfig: {
      method: 'GET',
      url: 'https://api.example.com/resource',
      authRef: '',
      timeoutMs: 10000,
      retryAttempts: 3,
      backoff: 'exponential',
      circuitFailureThreshold: 5,
      circuitOpenMs: 30000,
    },
  },
  {
    type: 'paginate_request',
    label: 'Paginate Request',
    category: 'Requests',
    defaultConfig: {
      method: 'GET',
      url: 'https://api.example.com/resources',
      authRef: '',
      strategy: 'next_url',
      itemsPath: 'body.items',
      nextCursorPath: 'body.next',
      hasMorePath: 'body.has_more',
      maxPages: 25,
      pageSize: 100,
      timeoutMs: 10000,
      retryAttempts: 3,
      backoff: 'exponential',
    },
  },
  {
    type: 'python_request',
    label: 'Python Request',
    category: 'Requests',
    defaultConfig: {
      functionName: 'custom_request',
      timeoutMs: 10000,
      retryAttempts: 3,
      backoff: 'exponential',
      code: 'def custom_request(context):\n    return {"status_code": 200, "body": {}}\n',
    },
  },
  {
    type: 'invoke_workflow',
    label: 'Invoke Workflow',
    category: 'Control',
    defaultConfig: {
      targetWorkflowId: '',
      targetWorkflowVersionId: '',
      publishedOnly: true,
      inputMode: 'inherit',
      inputSource: 'vars.input',
    },
  },
  {
    type: 'auth',
    label: 'Auth',
    category: 'Auth',
    defaultConfig: {
      authList: [
        {
          name: 'default',
          authType: 'bearer',
          tokenVar: 'vars.token',
          headerName: 'Authorization',
        },
      ],
      authType: 'bearer',
      tokenVar: 'vars.token',
      headerName: 'Authorization',
    },
  },
  {
    type: 'parameters',
    label: 'Parameters',
    category: 'Utility',
    defaultConfig: {
      parameters: [
        { name: 'date', type: 'string', defaultValue: '', description: 'Date parameter' },
      ],
    },
  },
  { type: 'save', label: 'Save', category: 'Save', defaultConfig: { key: 'result', from: 'nodes.form_request.output' } },
  { type: 'delay', label: 'Delay', category: 'Utility', defaultConfig: { ms: 250 } },
  { type: 'raise_error', label: 'Raise Error', category: 'Utility', defaultConfig: { message: 'Failed validation.' } },
];
